language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: hhvm  

before_install:
  - composer self-update
  - composer install --dev -n --prefer-source

before_script:
  - gem install mailcatcher
  - phpenv config-add travis.php.ini
  - mkdir -p resources/logs resources/tmp
  - mailcatcher --http-ip 0.0.0.0 --smtp-ip 0.0.0.0

script:
  - phpunit

addons:
  code_climate:
    repo_token:
      secure: "Cw8PcwP/1vC0OwHCoXMKh+wSOMzvOZKjgP0w1UbJtZ6SsRZnqilEhPdqbxS04W9BRwuiMAuMQ6wtvUKPkRJA6w9bNaSPfL4kpwz12Q16WIIL3GlH0M7XUrRktStYmtrEPlmRmTWgUWTF8e2g/YCi6HiNyesKNJvLFXZpH4K0zL8="

after_script:
  - php vendor/bin/coveralls -v
  - php vendor/bin/test-reporter --stdout > codeclimate.json
  - 'curl -X POST -d @codeclimate.json -H "Content-Type: application/json" -H "User-Agent: Code Climate (PHP Test Reporter v1.0.1-dev)"  https://codeclimate.com/test_reports'
  - cat resources/logs/*
